### ISSUE TITLE
`pip install smot` doesn't install dependencies

### ISSUE THREAD

**Issue by Bisaloo** [arendsee/jon#1]
I tried running:

```sh
pip install smot
smot -h
```

and got the following error:

> Traceback (most recent call last):
  File "/usr/local/bin/smot", line 5, in <module>
    from smot.main import main
  File "/usr/local/lib/python3.8/dist-packages/smot/__init__.py", line 27, in <module>
    from smot.parser import read_file, read_text
  File "/usr/local/lib/python3.8/dist-packages/smot/parser.py", line 4, in <module>
    import parsec as p
ModuleNotFoundError: No module named 'parsec'

`pip` is usually able to handle dependency install on its own which suggests a specific issue with the packaging here.

I'm not 100% sure but I *think* it's supposed to be `install_requires` instead of `installation_requires` here:

https://github.com/flu-crew/smot/blob/adee256c63df3ca1ceb34125e60b22a5bb24bf55/setup.py#L24

More info here: https://packaging.python.org/en/latest/discussions/install-requires-vs-requirements/

**Comment by arendsee** [comment]
@Bisaloo Thanks, I fixed the `install_requires` entry. For some reason, a local install of smot will still not automatically install parsec. However, when I manually install parsec (`pip install parsec`) everything works fine. Also, when I uninstall the other dependency, `click`, and reinstall smot, `click` is automatically installed. I'm not sure why `click` works but `parsec` does not.

**Comment by Bisaloo** [comment]
You have a chicken and egg problem because you use `smot.version` in your `setup.py`:

https://github.com/flu-crew/smot/blob/dbaf1146ce0d41da8fd3b2096e79087c4d073814/setup.py#L3

`smot.version` calls `__init__`, which in turn calls `smot.parser`, which requires `parsec`.

**Comment by arendsee** [comment]
@Bisaloo Good point. I believe I've fixed the issue by explicitly reading the version file and executing it. This should avoid the execution of __init__.py.
