### ISSUE TITLE
Test examples of part of the continuous integration

### ISSUE THREAD

**Issue by Bisaloo** [arendsee/jon#5]
I played around a bit more with the program and found an example that doesn't run. 

> smot color branch mono --factor-by-field 1 -c colormap foo.tre | smot push

in `smot color -h`

There might be more errors in other places.

It would be good to add the examples to your continuous integration set up to ensure the documentation is always providing correct examples.

This is part of https://github.com/openjournals/joss-reviews/issues/4193.

**Comment by arendsee** [comment]
The examples are correct, you just need to substitute real files. I assume the error message that was raised said that the `colormap` or `foo.tre` files did not exist?

**Comment by arendsee** [comment]
I just added automatic tests of the examples. And actually you were right about that example being incorrect, it needs to be `smot color push`.
